public class Bearer
{
	private static final String bearer = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImI1NDRkYTQ2LWNlNmYtNDEzZi1iOTA4LTI1NzMxYTAwNTk2MyIsImlhdCI6MTY1NzA1MTc4Nywic3ViIjoiZGV2ZWxvcGVyLzRhNmIzZDczLTMyZjktNDRkMS0xMGMzLWMzOTcxMDA2YzI4YiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjc5LjMzLjIyMS4xMzEiLCI3OS41My4xNTQuMjE4Il0sInR5cGUiOiJjbGllbnQifV19.obI59OwVvpp04HxbWvvarg1pnSklIWErHN8UxkUfTxrHYtJkZdyipxpWbV0IfegOnZuPi4eyIK8tiRocV9H4tw";
	
	public Bearer() {}
	
	public String getBearer()
	{
		return bearer;
	}
}
