public class Bearer
{
	private static final String bearer = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjRmZmY4YzY1LTQzZTctNGM5YS1iZGYyLTI5MjY1ZWQwYzEzOSIsImlhdCI6MTY1OTMzODQ0NSwic3ViIjoiZGV2ZWxvcGVyLzRhNmIzZDczLTMyZjktNDRkMS0xMGMzLWMzOTcxMDA2YzI4YiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjk1LjIzOS4xODYuMTM0Il0sInR5cGUiOiJjbGllbnQifV19.stC6NyLm1o9IKsoyK_2V7DyGld1dhqattv6pvOGIJzD5_757VFwEjA-gG9zeOh2N3Jej3Vi5npQUidYYiqB6mA";
	
	public Bearer() {}
	
	public String getBearer()
	{
		return bearer;
	}
}
